######################## default configuration ####################
baseURL = "https://gatherings.innersourcecommons.org/tokyo-2024"
title = "InnerSource Gathering Tokyo 2024"
themesDir = "../themes"
theme = "gathering-theme"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Speakers"
  URL = "speaker"
  weight = 3

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 4
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

#################### default parameters ################################
[params]
logo = "images/gathering-tokyo-2024.png"
home = "Home"
# Meta data
description = "InnerSource Gathering Tokyo 2024"
author = "InnerSource Gathering Organizors"
# email address
email = "gathering@innersource.org"
# Google Analitycs
google_analitycs_id = "" # your id
# search for blog page
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Connpassで参加登録"
link = "https://innersourcecommons.connpass.com/event/"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "35.6678347"
map_longitude = "139.7500377,15"
map_marker = "images/marker.png"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/InnerSourceJP"

[[params.social]]
icon = "tf-ion-social-linkedin"
link = "https://www.linkedin.com/company/innersourcecommons/"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/@InnerSourceCommonsJapan"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1
home = "Home"
# footer content
footer_content = """
InnerSource Commons は、InnerSource のグローバルコミュニティです。
2015年に設立され、現在では750以上の企業、学術機関、政府機関から3000人以上の個人をサポートし、つなぎ合わせています。
InnerSource の始め方やベストプラクティスを共有し、InnerSource の価値観や原則についての議論を促進しています。
"""
# copyright
copyright = """
[行動規範](https://innersourcecommons.org/ja/about/codeofconduct/) | Copyright &copy; 2024
"""

############################# Organizers ############################
# Executive Members
[params.organizers]
enable = true
head = "Organizers"

[[params.organizers.members]]
image = "https://pbs.twimg.com/profile_images/1430521969791750160/gQC7UC5c_400x400.jpg"
profile = "https://twitter.com/bory_kb"

[[params.organizers.members]]
image = "https://avatars.githubusercontent.com/u/101680007?v=4"
profile = "https://github.com/daichi-tazawa"

[[params.organizers.members]]
image = "images/organizers/jimmysharp.png"
profile = "https://github.com/jimmysharp"

[[params.organizers.members]]
image = "https://pbs.twimg.com/profile_images/1289149372769243142/rfR3Phkv_400x400.jpg"
profile = "https://twitter.com/jnymyk"

[[params.organizers.members]]
image = "images/organizers/koji-komatsu.png"
profile = "https://github.com/koji-komatsu"

[[params.organizers.members]]
image = "images/organizers/kyuukix.png"
profile = "https://github.com/kyuukix"

[[params.organizers.members]]
image = "https://pbs.twimg.com/profile_images/1590649013086191616/vzvc-A4y_400x400.jpg"
profile = "https://twitter.com/piyonakajima"

[[params.organizers.members]]
image = "images/organizers/rashikawat.png"
profile = "https://github.com/rashikawat"

[[params.organizers.members]]
image = "https://pbs.twimg.com/profile_images/1544322378750038016/hZIr8heH_400x400.jpg"
profile = "https://twitter.com/yuhattor"